app_title="Mosquitto manažer"

mainmenu_pwdfile    ="Soubor s hesly "
mainmenu_aclfile    ="ACL soubor     "
mainmenu_ucnt       ="Počet uživatelů"

err="CHYBA"
err_menuid = "Menu ID nenalezeno"
tx_yes="Ano"
tx_no="Ne"
tx_ena="Zapnut"
tx_dis="Vypnut"

nfo="INFO"
back="Zpět"
yesother="( a=Ano ostatní=Ne )"
keychoice="Stiskni klávesu/y volby"
pressakey="Stiskni klávesu"

choiceY="Aa"
choiceQ="Zz"
choiceNew="N"
choiseUserFile="S"
choiceUsers="Uu"
choiceACL="Aa"
choiceResMsq="Rr"
choiceQuittx="Kk"
choiceDelUs="Ss"
choicepwdchng="Hh"
choiceACLnewbl="Nn"
choiceACLnewtp="Nn"
choiceACLdelall="Vv"

user="uživatel"
users_manage="Správa uživatelů"
user_edit="Editace uživatele"
user_new="Nový uživatel"
user_file="Nenalezen soubor s uživately/hesly, vytvořit ?"
user_create="Vytvoř nového uživatele, napiš '"+choiceQ[0]+"' pro zrušení"
user_enter="Napiš nového uživatele (znaky: a-z 0-9 _ ), min. délka je 4 znaky"
user_lng_err="Minimální délka uživatelského jména jsou 4 znaky"
user_err_word="Zadáno zakázané slovo"
user_err_char="Uživatelské jméno obsahuje zakázané znaky"
user_exists="Uživatel již existuje, vytvoř jiného"
user_mng_acl="Správa ACL uživatelů"
user_del="Opravdu smazat uživatele"

pwd_err_char="Byly použity zakázané znaky v hesle"
pwd_new="Napiš heslo ( znaky: a-z 0-9 _ & # @ * - ) min. délka 6 znaků"
pwd_lng="Min. délka hesla je 6 znaků"
pwd_again="Napiš heslo znovu pro ověření"
pwd_neq="Hesla se neshodují"
pwd_us="Změna hesla pro uživatele"

line="--------------------------"
starline="*************************"

menu_users="Uživatelé"
menu_acl="ACL"
menu_res_msq="Restartuj Mosquitto"
menu_delUs="Smazat uživatele"
menu_chngpwd="Změnit heslo"

acl_newblock="Vytvoř nový ACL blok pro uživatele"
acl_forusr="Pro uživatele"
acl_line="Řádek"
acl_newtp="Nový topic/pattern"
acl_delall="Smazat celý blok uživatele"
acl_mnglines="Správa řádků ACL pro uživatele"
acl_qdellall="Opravdu smazat všechny řádky ACL pro uživatele"
acl_moavailusr="V souboru hesel není uživatel, který by neměl již vytvořené ACL. Vytvoř nového uživatele a ten se tu zobrazí."
acl_addblforus="přidat pro uživatele"
acl_newusrbl="Vytvořit nový ACL blok pro uživatele"
acl_newusrblnfo="Zobrazeny jsou jen uživatelé, kteří ještě nemají ACL blok vytvořený"
acl_addattr="Přidat topic atribut"
acl_atrsel="Vybráno"
acl_line_nfo1="INFO: $SYS = systémový root topic, %%c = uživatelské ID, %%u = uživ. jméno, # = na konci cesty znamená vše: tj. pth/# akceptuje pth/x pth/y atd."
acl_line_nfo2="INFO: pokud topic path se rovná znak # , tak je povolen jakýkoliv topic"
acl_typepath="Napiš topic (příklad: mytopic/read )"
acl_path_forb="Topic obsahuje zakázané znaky ( mezera * + - )"
alc_path_lng_er="CHYBA: min délka je jeden znak"
acl_editLine="Upravit ACL řádku"
acl_qattris="Atribut {} je {}"

choiceACLlineed="Uu"
choiceACLlinedel="Ss"
choiceAttrEna="Zz"
acl_line_ed="Upravit řádek"
acl_line_del="Smazat řádek"
acl_editusrline="ALC úprava řádku pro uživatele {}, řádek: {}"
acl_qline_del="Opravdu smazat řádek"
acl_changeattr="Změnit na: klávesa '"+choiceAttrEna[0]+"'=zapnuto,  ostatní klávesy=vypnuto"
acl_curline="Aktuální řádka"
acl_lineto="Změnit na"

msqt_restart="Restartuji Mosquitto, počkej dokud se nezobrazí: Stiskni klávesu"

quittx = "Konec"